# Generated by Django 3.2.6 on 2021-09-15 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_organizer'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='organizer_email',
            field=models.EmailField(default='test@mail.com', max_length=254),
            preserve_default=False,
        ),
    ]
